name: Continuous Integration

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true # so that coverage is not interactive
      
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
