name: Continuous Integration

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main, workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache node_modules       # Makes npm ci run faster
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json')}}
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true                      # so that coverage is not interactive
      - name: Upload Test coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: coverage
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Upload Build folder
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
      - name: ZIP Assets
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          zip -r build.zip ./build
          zip -r coverage.zip ./coverage

      - name: Create a Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Coverage Reports
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Open Issue
        if: failure() && github.event_name == 'pull_request'
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_.",
            "assignees": ["${{ github.event.pull_request.user.login }}"]
            }'
      
      - name: Send Error Message
        if: failure() && github.event_name == 'pull_request'
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            **ERROR Message**
            The ${{ github.event_name }} to ${{ github.base_ref }} from ${{ github.head_ref }} has failed
            Workflow: ${{ github.workflow }}
            Job ID: ${{ github.job }}
            Repository: ${{ github.repository }}
            Job Status: ${{ job.status }}
      
      - name: Send Error Message
        if: failure() && github.event_name == 'push'
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          bold: "ERROR Message"
          message: |
            ERROR Message
            The ${{ github.event_name }} to ${{ github.ref }} has failed
            Workflow: ${{ github.workflow }}
            Job ID: ${{ github.job }}
            Repository: ${{ github.repository }}
            Job Status: ${{ job.status }}
        
      - name: Successful Message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            **Notification Message**
            Your ${{ github.event_name }} to ${{ github.head_ref }} has been successfully made
            Workflow: ${{ github.workflow }}
            Job ID: ${{ github.job }}
            Repository: ${{ github.repository }}
            Job Status: ${{ job.status }}